services:
   uecode_image.routing_loader:
        class: Uecode\Bundle\Routing\RouteLoader
#        arguments: ['upload', UecodeImageBundle:Uploader:Upload]
        tags:
            - { name: routing.loader }